### PR TITLE
Sorting and Filtering Implementation Rewritten

### PR DESCRIPTION
**Pull request by chrisrchar**

### CODE REVIEW

**Review by ingarcia1 — APPROVED** [review]
Addresses are now valid!

**Review by jaybouche — APPROVED** [review]

**Review by jbennatt — APPROVED** [review]
Tested on my machine inside Zoom chat. All previous features worked and dummy users are able to log in and save cars, etc.

**Review by sfjsss — APPROVED** [review]
looks good

**Review by sfjsss — APPROVED** [review]
looks good

**Pull request merged**
