### PR TITLE
2002 uta tianyu li add address validation

### PR DESCRIPTION
**Pull request by sfjsss**
created a new package: com.revature.beans.geolocationResponse
It contains models which match the JSON we expect from GeoLocation API response

created a new package: com.revature.validators
It contains a custom validator (UserVaidator) which is going to send an HTTP request to GeoLocation API and validate the address

Autowired UserValidator in UserController so the controller has access to this custom validator

Modified updateUser method in UserController
Added BindingResult to gain access to the validation information
called UserValidator to validate the address
Serialized BindingResult so it can be passed in response
Modified return from updated user object to responseEntity which contains validation information

Modified addUser method in UserController
called UserValidator to validate the address

### CODE REVIEW

**Review by carolynrehm — COMMENTED** [review]
Does src/main/java/com/revature/Driver.java need to be included in this PR? seems like some unused imports. Also is there a way that we can configure the object mapping so that the java classes supporting the google maps api responses so that the fields can still follow java naming conventions?

**Comment by sfjsss** [comment]
@carolynrehm 
I have removed the unused import in Driver.java
I added @JsonProperty on corresponding getters and setters in the API response matching objects and changed class member name to follow Java convention
I removed @Notblank annotation on wAddress in User model because it is actually an optional field
I optimized the address validation logic to make sure only exact match address pass the validation
I tested all the above modifications and made sure all features still work

**Comment by jbennatt** [comment]
What testing can we do to verify whether or not this is working?

**Comment by sfjsss** [comment]
on signup or update location in profile, try to enter some invalid address like 23 tomato street, tomato city
The front end wont show anything cuz we havent integrated with front end, but looking at spring console, if the address is invalid, it will show 
validation result is org.springframework.validation.BeanPropertyBindingResult: 5 errors
if it is a valid address, should show 0 errors

**Comment by sfjsss** [comment]
@jbennatt 
I'm not sure how to test the validator directly. But you can test the controller methods that are using the validator. For example, the updateUser in UserController, if the user object being passed in doesn't have a valid address, the hashMap validationInfo which seralizes the BindingResult will contain 5 sets of key value pair with keys (hZip, hCity, hAddress, wAddress, hState) and values of "Invalid".

**Review by jaybouche — COMMENTED** [review]
When entering invalid address I can see the logs of it being invalid type; however, the data still persists and is saved to the user.

**Comment by sfjsss** [comment]
@jaybouche 
Yes. This branch only adds the address validation logic but it doesn't alter the result of requests. To do that is pretty simple tho, just need to add an if-logic to check if the size of the validationInfo (which is a hashMap that serializes BindingResult which contains all validation info including address validation) is equal to 0, if it is 0 then execute the data persist code. But this logic belongs to another user story (refactor form validation) of our team, will create a pull request for that feature branch after this one is merged.

**Comment by jbennatt** [comment]
We need a way to communicate to the front end that the input address is correct or incorrect. That's a simple boolean: true or false, that's what the REST call should return. If it's correct, save it, if not, don't and return "false".

**Review by jbennatt — COMMENTED** [review]
If what's there is part of what's needed, but not the whole thing, let's please go ahead and merge it so that everyone has at least that. If there is more to be done, that can be done in a later git push--I think it's fine to have partial progress.

**Comment by sfjsss** [comment]
it's going to return a json which contains key-value pairs indicating the validation status on each field. If there is no validation error its going to be an empty json, if there is any, say the address is invalid, the json will be like {hZip: "invalid", hCity: "invalid", hAddress: "invalid", wAddress: "invalid", hState: "invalid"} I can simplify it to {address: "invalid"} but I was trying to match these key-value pair to the fields on the forms.

**Review by jaybouche — APPROVED** [review]
sounds good.

**Review by jbennatt — APPROVED** [review]
OK, that sounds reasonable to me, although, I do think you should specify the wrong field (is that difficult--if so, just specify them all as invalid).

**Comment by sfjsss** [comment]
So the way geoCoding api works is that we send in an address (a combination of address, city,  zipcode, state) and it returns us the matching results. My logic checks if there is more than one result, or there is no result, or there is only one result but is partially matched. if those are the case that means our combined address is invalid as a whole. So technically all fields (address, city, zipcode, state) are invalid.

I also thought about it and I agreed that separating out the logic that decides whether persist data or not doesn't make sense, so I added those code and made another push.

So now what this branch of code will do is that it checks if all form fields (including address) are valid on sign up form and profile location form, if they are, data will be persisted and client will receive an empty json, if they are not valid, data will not be persisted and client will receive a json with field names that failed the validation as keys, and the failing type as value.

What this branch of code doesn't do is that it doesn't provide UI feedback regarding whether the form passed server-side validation. We will start working on this feature when Jay's bug fixing code is merged. This branch of code also doesn't add any extra/refactor validation on forms other than sign up and profile location. The form validation refactor is being worked as another user story in my team and is on another branch which i will make a pull request once this one is merged.

**Review by chrisrchar — COMMENTED** [review]
I pulled the code and couldn't get any valid addresses to show up as valid. Tried about 3 or 4 different ones and none of them worked. The code looks fine, so is this a problem with our API key not having the right permissions? Just wondering if you know about this.

**Comment by sfjsss** [comment]
yea I don't think the company api key currently has geocoding enabled. The address validation uses that service. im using my own key atm

**Review by chrisrchar — APPROVED** [review]
Okay, sounds good

**Review by carolynrehm — COMMENTED** [review]
This looks good, lets just remove the commented out code from the UserController and the single line comments from the User class and it should be good to go

**Pull request merged**
